name: deploy to test instance
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/psurvey    
          cd /apps/github-workflows/mhealth-apps/psurvey/
          git pull origin cicd
          git status
          cp  /apps/dockerApps/psurvey/python.dockerfile /apps/github-workflows/mhealth-apps/psurvey
          cp  /apps/dockerApps/psurvey/nginx.dockerfile /apps/github-workflows/mhealth-apps/psurvey
          cp  /apps/dockerApps/psurvey/docker-compose.yml /apps/github-workflows/mhealth-apps/psurvey
          cp  /apps/dockerApps/psurvey/secrets.json /apps/github-workflows/mhealth-apps/psurvey
          cp -r /apps/dockerApps/psurvey/docker/ /apps/github-workflows/mhealth-apps/psurvey
          docker-compose down
          docker-compose rm -f
          docker-compose up --build -d
